In [1]:
import tensorflow as tf

# Make matrix

* The data type can be changed by typing [.]

In [8]:
matrix_1 = tf.constant([[3., 3.]])
matrix_2 = tf.constant([[2., 2.]])
print(matrix_1)
print(matrix_2)

tf.Tensor([[3. 3.]], shape=(1, 2), dtype=float32)
tf.Tensor([[2. 2.]], shape=(1, 2), dtype=float32)


# To numpy

In [14]:
print(matrix_1.numpy())
print(matrix_2.numpy())

[[3. 3.]]
[[2. 2.]]


# Dot product
* Can not calculate using diffrent type of data   
ex) int32, float32

In [11]:
tf.matmul(matrix_1, tf.transpose(matrix_2))

<tf.Tensor: id=10, shape=(1, 1), dtype=float32, numpy=array([[12.]], dtype=float32)>

# Dtype str

In [20]:
tensor_str = tf.constant("Hello")
print(tensor_str)
print(tensor_str.numpy())
print(tensor_str.numpy().decode("utf-8"))
print(tensor_str.numpy().decode("cp932"))

tf.Tensor(b'Hello', shape=(), dtype=string)
b'Hello'
Hello
Hello


# tf.function

In [27]:
import timeit

def a_regular_function(x, y, b):
    return tf.matmul(x, y) + b

a_function_that_uses_a_graph = tf.function(a_regular_function)

x1 = tf.constant([[1., 2.]])
y1 = tf.constant([[2.], [3.]])
b1 = tf.constant(4.0)

original_value = a_regular_function(x1, y1, b1).numpy()

tf_function_value = a_function_that_uses_a_graph(x1, y1, b1).numpy()

assert original_value == tf_function_value

In [29]:
def inner_function(x, y, b):
    return tf.matmul(x, y) + b

@tf.function
def outer_function(x):
    y = tf.constant([[2.], [3.]])
    b = tf.constant(4.0)
    return inner_function(x, y, b)


outer_function(tf.constant([[1., 2.]]))

<tf.Tensor: id=83, shape=(1, 1), dtype=float32, numpy=array([[12.]], dtype=float32)>

# tf.estimator

# tf.data.Dataset

# tf.distributed

# TensorFlow Extended(TFX)

# TensorFlow. js

# TensorFlow Lite

In [12]:
sess = tf.Session()

AttributeError: module 'tensorflow' has no attribute 'Session'

In [38]:
from glob import glob
import os
from tqdm import tqdm

import time
for i in tqdm(range(10)):
#     print(i)
    a = 9
    time.sleep(1)

100%|██████████████████████████████████████████████████████████████████████████████████| 10/10 [00:10<00:00,  1.01s/it]
